### ISSUE TITLE
Creating a PR is tricky

### ISSUE THREAD

**Issue by murzagalin** [icerockdev/libs.kmp.icerock.dev#48]
I want to add my library to the list. But I have no permission to push my branch to create a PR. 
How can I do this here?

**Comment by sya-ri** [comment]
@murzagalin You can fork and create a PR. like this: #50
![image](https://user-images.githubusercontent.com/34268371/190176087-005987d0-e6d8-4e22-99ad-f335dbaccdbc.png)
